### ISSUE TITLE
VirtualEditor works in Web-Instance but not in localhost deployment.

### ISSUE THREAD

**Issue by FantasticoFox** [inblockio/aqua-PKC#102]
![image](https://user-images.githubusercontent.com/45313235/146930278-8c436007-bfae-4068-8bca-eef01856e3e3.png)

The 'new' VisualEditor is a huge UX improvement for new users. Therefore we want to activate it and include it for the Micro-PKC-v1.1.0-alpha release.

**Comment by rht** [comment]
You need to document the `require local` (or something, I don't remember) solution patch for Apache here.

**Comment by FantasticoFox** [comment]
I actually don't know. So will wait for BlueSpice to answer.

**Comment by FantasticoFox** [comment]
In MW1.39 it works. So issue now obsolete.
