### ISSUE TITLE
pkc setup: Sometimes curl of aqua-white-1024x1024-32x32.png blocks the install indefinitely

### ISSUE THREAD

**Issue by rht** [inblockio/aqua-PKC#125]
https://github.com/inblockio/aqua-PKC/blob/14f77b879783296a5bf9b56f399a97537fc45634/pkc#L328
There needs to be a timeout, and a message to the user when the download fails. But it shouldn't block the rest of the installation.

**Comment by FantasticoFox** [comment]
Closed with 6d981d7d774ff16c1b729c25806acbbb00c2b7b2
