### ISSUE TITLE
Installation method for OpenIDConnect & PluggableAuth MW extension is not sustainable

### ISSUE THREAD

**Issue by rht** [inblockio/aqua-PKC#129]
The links in https://github.com/inblockio/aqua-PKC/blob/93a6e41657503f33c576ffa7f5c0245fa6df1b06/aqua/install_pkc.sh#L75-L78 were recently garbage-collected by the MW website, and I had to manually update them just now. Needs a way to automatically get the latest compatible version, or to have a pinned stable version. Not sure how.

**Comment by it-spiderman** [comment]
Done with 

https://github.com/inblockio/aqua-PKC/pull/130
https://github.com/inblockio/aqua-docker-mediawiki/pull/6
